name: Maven CI/CD

on: [ push, pull_request ]

jobs:
  package:
    runs-on : ubuntu-latest
    steps :
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-${{ secrets.CACHE_VERSION }}
      - name: Append 'SNAPSHOT' to version if 'push' happened on 'main'
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          mvn versions:set -DremoveSnapshot
          mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
          VERSION=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
          mvn versions:set -DnewVersion=$VERSION-SNAPSHOT
      - name: Append branch name to version if 'push' did not happen on 'main' or a tag
        if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')}}
        run: |
          mvn versions:set -DremoveSnapshot
          mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
          VERSION=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
          mvn versions:set -DnewVersion=$VERSION-${GITHUB_REF##*/}
      - name : Compile
        run: mvn clean package
      - name: Deploy
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' ||  startsWith(github.ref, 'refs/tags/')) }}
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
